import { NextResponse } from "next/server";

import { fail, handle, unauthorized } from "@/lib/admin/api";
import { deleteBlob, revalidateGallery } from "@/lib/admin/gallery";
import { isBlobUrl, photoIdInput } from "@/lib/admin/gallery-input";
import { firstIssue } from "@/lib/admin/item-input";
import { prisma } from "@/lib/prisma";

/**
 * Removes a photograph from the gallery, and its file from the store.
 *
 * The file goes first: a row with no file behind it would leave a hole on the
 * public page, while a file with no row is only a file nobody can reach. If the
 * store refuses, the row stays and the failure is reported, so pressing Delete
 * again finishes the job — deleting an already-deleted blob is not an error.
 *
 * The twelve photographs that ship with the app are rows like any other, but
 * they are files in public/ rather than uploads, so there is nothing in the
 * store to remove and the row is simply dropped.
 */
export async function DELETE(
  _request: Request,
  // Spelled out rather than taken from `RouteContext`, whose union of known
  // routes is generated by a build and so does not yet include this one.
  context: { params: Promise<{ id: string }> },
) {
  return handle("DELETE /api/admin/gallery/[id]", async () => {
    const denied = await unauthorized();
    if (denied) return denied;

    const { id } = await context.params;

    const parsed = photoIdInput.safeParse(id);
    if (!parsed.success) {
      return fail(firstIssue(parsed.error), 400);
    }

    const photo = await prisma.galleryImage.findUnique({
      where: { id: parsed.data },
      select: { url: true },
    });

    if (!photo) {
      // Already gone. Say so rather than pretending, so the manager can explain
      // why the photograph it was looking at is not there any more.
      return fail("That photograph no longer exists.", 404);
    }

    if (isBlobUrl(photo.url)) {
      await deleteBlob(photo.url);
    }

    await prisma.galleryImage.delete({ where: { id: parsed.data } });

    revalidateGallery();

    return NextResponse.json({ ok: true });
  });
}
